// Material Symbols (Outlined, 24px) を取得して public/icons.mjs に埋め込む。
// 実行: npm run icons
import { writeFile } from 'node:fs/promises';

const COMMIT = '27e9ef1dbeedc13d682fece4a58e1eda4cb0961a';
const NAMES = [
  'library_music', 'settings', 'arrow_back', 'queue_music', 'repeat',
  'play_arrow', 'pause', 'skip_next', 'skip_previous', 'shuffle',
  'more_horiz', 'download', 'download_done', 'progress_activity',
  'sort', 'folder', 'add', 'delete', 'close', 'keyboard_arrow_down',
  'drag_handle', 'playlist_add', 'playlist_play', 'info', 'share', 'upload',
  'refresh', 'remove', 'music_note', 'key', 'check', 'cloud_off', 'check_circle', 'radio_button_unchecked', 'lyrics',
];

const out = {};
for (const name of NAMES) {
  const url = `https://raw.githubusercontent.com/google/material-design-icons/${COMMIT}/symbols/web/${name}/materialsymbolsoutlined/${name}_24px.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${name}: ${res.status}`);
  const svg = (await res.text()).trim()
    .replace('<svg ', '<svg class="material-icon" aria-hidden="true" focusable="false" ');
  out[name] = svg;
}
const body = `// Google Material Symbols, Apache-2.0. See vendor/material-symbols/. Generated by scripts/icons.mjs.
const icons = ${JSON.stringify(out, null, 2)};
export function icon(name) { return icons[name] || ''; }
`;
await writeFile(new URL('../public/icons.mjs', import.meta.url), body);
console.log(`wrote ${NAMES.length} icons`);
